{
  "name": "Economic Report - Jojoba",
  "nodes": [
    {
      "parameters": {
        "rule": {
          "interval": [
            {
              "field": "minutes",
              "value": 5
            }
          ]
        }
      },
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "position": [-400, 32],
      "typeVersion": 1.3,
      "id": "schedule-trigger"
    },
    {
      "parameters": {
        "method": "POST",
        "url": "http://host.docker.internal:8000/api/v1/agent/webhook/next",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "X-API-Key",
              "value": "jojoba-webhook-key-2024"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "options": {}
      },
      "name": "Get Next Question",
      "type": "n8n-nodes-base.httpRequest",
      "position": [0, 0],
      "typeVersion": 4.4,
      "id": "http-request-next"
    },
    {
      "parameters": {
        "conditions": {
          "options": [
            {
              "key": "status",
              "operation": "notEqual",
              "value": "error"
            }
          ]
        }
      },
      "name": "Check Status",
      "type": "n8n-nodes-base.if",
      "position": [200, 0],
      "typeVersion": 2.0,
      "id": "if-check-status"
    },
    {
      "parameters": {
        "fromEmail": "youremail@gmail.com",
        "toEmail": "={{ $json.emails ? $json.emails.join(',') : 'default@example.com' }}",
        "subject": "=📊 Jojoba Economic News - {{ $json.question }}",
        "html": "=<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"UTF-8\">\n<title>Jojoba Economic News</title>\n<style>\n    body { font-family: Arial, sans-serif; background: #f5f7fa; margin: 0; padding: 0; }\n    .container { max-width: 620px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; }\n    .header { background: #0f1a2e; padding: 20px 25px; }\n    .header h1 { margin: 0; color: #ffffff; font-size: 20px; }\n    .content { padding: 20px 25px; }\n    .question-box { background: #f0f4fe; border-radius: 6px; padding: 12px 16px; margin-bottom: 18px; border-left: 3px solid #1a5c9e; }\n    .question-box .label { font-size: 10px; text-transform: uppercase; color: #1a5c9e; font-weight: 700; }\n    .question-box .text { font-size: 15px; font-weight: 500; color: #0f1a2e; margin: 4px 0 0 0; }\n    .answer-box { margin: 18px 0; }\n    .answer-box .label { font-size: 10px; text-transform: uppercase; color: #6b7a8a; font-weight: 700; display: block; margin-bottom: 5px; }\n    .answer-box .content { background: #fafbfc; border-radius: 6px; padding: 14px 16px; border: 1px solid #eaeef2; font-size: 14px; line-height: 1.6; color: #1e2a3a; white-space: pre-wrap; word-wrap: break-word; }\n    .stats { background: #f8f9fb; border-radius: 6px; padding: 12px 16px; border: 1px solid #eaeef2; }\n    .stat { display: inline-block; margin-right: 20px; }\n    .stat .value { font-weight: 600; color: #1a5c9e; }\n    .footer { background: #f8f9fb; padding: 14px 25px; border-top: 1px solid #eaeef2; font-size: 11px; color: #7a8a9a; }\n</style>\n</head>\n<body>\n<div class=\"container\">\n    <div class=\"header\">\n        <h1>📊 Jojoba Economic News</h1>\n    </div>\n    <div class=\"content\">\n        <div class=\"question-box\">\n            <div class=\"label\">📋 Today's Question</div>\n            <div class=\"text\">{{ $json.question || 'No question' }}</div>\n        </div>\n        <div class=\"answer-box\">\n            <span class=\"label\">💡 Analysis</span>\n            <div class=\"content\">{{ $json.response || 'No answer' }}</div>\n        </div>\n        <div class=\"stats\">\n            <div class=\"stat\">⏱ <span class=\"value\">{{ $json.processing_time || 0 }}s</span></div>\n            <div class=\"stat\">🔄 <span class=\"value\">{{ $json.iterations || 0 }}</span> iterations</div>\n            <div class=\"stat\">📊 <span class=\"value\">{{ $json.queue_remaining || 0 }}</span> remaining</div>\n        </div>\n    </div>\n    <div class=\"footer\">\n        <strong>⚠️ Disclaimer:</strong> Not financial advice. For educational purposes only.<br>\n        Generated by Jojoba Economic Advisor AI\n    </div>\n</div>\n</body>\n</html>",
        "options": {}
      },
      "name": "Send Email",
      "type": "n8n-nodes-base.emailSend",
      "position": [400, 0],
      "typeVersion": 2.1,
      "id": "email-send",
      "credentials": {
        "smtp": {
          "id": "your-smtp-credential-id",
          "name": "Gmail SMTP"
        }
      }
    },
    {
      "parameters": {
        "method": "POST",
        "url": "http://host.docker.internal:8000/api/v1/agent/webhook",
        "sendHeaders": true,
        "sendBody": true,
        "bodyParametersJson": "={\"status\": \"completed\", \"emails_sent\": {{ $json.sent_count || 0 }}, \"execution_id\": \"{{ $execution.id }}\"}",
        "headerParameters": {
          "parameters": [
            {
              "name": "X-API-Key",
              "value": "jojoba-webhook-key-2024"
            }
          ]
        }
      },
      "name": "Log Completion",
      "type": "n8n-nodes-base.httpRequest",
      "position": [600, 0],
      "typeVersion": 4.4,
      "id": "http-log-completion"
    }
  ],
  "connections": {
    "Schedule Trigger": {
      "main": [[{"node": "Get Next Question", "type": "main", "index": 0}]]
    },
    "Get Next Question": {
      "main": [[{"node": "Check Status", "type": "main", "index": 0}]]
    },
    "Check Status": {
      "main": [
        [{"node": "Send Email", "type": "main", "index": 0}],
        [{"node": "Log Completion", "type": "main", "index": 1}]
      ]
    },
    "Send Email": {
      "main": [[{"node": "Log Completion", "type": "main", "index": 0}]]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  }
}